pipeline {
    agent any
    
    stages {
        stage('Build Backend') {
            steps {
                dir('FitLifePro/server-java') {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }
        
        stage('Build Frontend') {
            steps {
                dir('FitLifePro/client') {
                    bat 'npm ci'
                    bat 'npm run build'
                }
            }
        }
        
        stage('Docker Build') {
            steps {
                dir('FitLifePro') {
                    bat 'docker-compose build'
                }
            }
        }
    }
}
